name: K8s Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install MicroK8s
        run: |
          sudo snap install microk8s --classic
          sudo microk8s status --wait-ready
          sudo microk8s enable dns
          
      - name: Build and Import Docker image
        run: |
          docker build -t hello-k8s:latest .
          docker save hello-k8s:latest > hello-k8s.tar
          sudo microk8s ctr image import hello-k8s.tar
          
      - name: Deploy application
        run: |
          cat <<EOF | sudo microk8s kubectl apply -f -
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: hello-world
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: hello-world
            template:
              metadata:
                labels:
                  app: hello-world
              spec:
                containers:
                - name: hello-world
                  image: hello-k8s:latest
                  imagePullPolicy: Never
                  ports:
                  - containerPort: 80
          EOF
          sudo microk8s kubectl expose deployment hello-world --port=80 --type=ClusterIP
          
      - name: Test deployment
        run: |
          # Wait for pod to be ready
          sudo microk8s kubectl wait --for=condition=ready pod -l app=hello-world --timeout=60s
          
          # Port forward in background
          sudo microk8s kubectl port-forward service/hello-world 8080:80 &
          sleep 5
          
          # Test the endpoint
          curl -s http://localhost:8080 | grep "Hello World from Kubernetes!"